// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHteHd7iQLUhOdu6tIyfd4ymOp3Tj16E',
    appId: '1:639961503690:web:1052e93801d9bb730f2133',
    messagingSenderId: '639961503690',
    projectId: 'final-project-8d4de',
    authDomain: 'final-project-8d4de.firebaseapp.com',
    storageBucket: 'final-project-8d4de.firebasestorage.app',
    measurementId: 'G-3W1XHYFTG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFM73XPP1ZarYL1JjwEjME52Ha9yG3Zq8',
    appId: '1:639961503690:android:44c6e2687e3d02e30f2133',
    messagingSenderId: '639961503690',
    projectId: 'final-project-8d4de',
    storageBucket: 'final-project-8d4de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGhZJl-qleXbs-YChM-WtY625_bfFTeY',
    appId: '1:639961503690:ios:2bd7c2e33ee432710f2133',
    messagingSenderId: '639961503690',
    projectId: 'final-project-8d4de',
    storageBucket: 'final-project-8d4de.firebasestorage.app',
    iosBundleId: 'com.example.landSladeGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaGhZJl-qleXbs-YChM-WtY625_bfFTeY',
    appId: '1:639961503690:ios:2bd7c2e33ee432710f2133',
    messagingSenderId: '639961503690',
    projectId: 'final-project-8d4de',
    storageBucket: 'final-project-8d4de.firebasestorage.app',
    iosBundleId: 'com.example.landSladeGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNHteHd7iQLUhOdu6tIyfd4ymOp3Tj16E',
    appId: '1:639961503690:web:8cbf8d2ad33acd610f2133',
    messagingSenderId: '639961503690',
    projectId: 'final-project-8d4de',
    authDomain: 'final-project-8d4de.firebaseapp.com',
    storageBucket: 'final-project-8d4de.firebasestorage.app',
    measurementId: 'G-3K1BS1SLJ5',
  );
}
